version: '3.9'

services:
  app:
    build:
      context: .
    image: anzu-info
    container_name: anzu-info
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
